name: Release Please

on:
  workflow_call:
    secrets:
      application-id:
        required: true
      private-key:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: "${{ secrets.release-please-application-id }}"
          application_private_key: ${{ secrets.release-please-private-key }}
          organization: ${{ github.repository_owner }}
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.get_token.outputs.token }}