name: Build, Test and Publish Rust Package

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory to run jobs from'
        default: '.'
        type: string
      run-audit:
        description: 'Run cargo-audit for security vulnerabilities'
        default: true
        type: boolean
      enable-cache:
        description: 'Enable caching of dependencies'
        default: true
        type: boolean
      publish-crates-io:
        description: 'Publish package to crates.io'
        default: false
        type: boolean
      upload-artifact:
        description: 'Upload build artifact'
        default: false
        type: boolean
      artifact-name:
        description: 'Name of the artifact to upload'
        type: string
        required: false
      artifact-path:
        description: 'Path to the artifact to upload'
        type: string
        required: false
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: false

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add clippy and rustfmt
        run: rustup component add clippy rustfmt

      - name: Cache dependencies
        if: ${{ inputs.enable-cache }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-

      - name: Check formatting
        working-directory: ${{ inputs.working-directory }}
        run: cargo fmt --all -- --check

      - name: Run linter (Clippy)
        working-directory: ${{ inputs.working-directory }}
        run: cargo clippy --all-targets -- -D warnings
      
      - name: Install cargo-audit
        if: ${{ inputs.run-audit }}
        run: cargo install cargo-audit

      - name: Run security audit
        if: ${{ inputs.run-audit }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo audit

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: cargo build --release

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: cargo test --release

      - name: Upload artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Validate package
        if: ${{ inputs.publish-crates-io }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo package

      - name: Publish to crates.io
        if: ${{ inputs.publish-crates-io }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo publish
