name: Build, Test and Publish Rust Package

on:
  workflow_call:
    inputs:
      rust-version:
        description: 'Rust version to use'
        default: 'stable'
        type: string
      build-target:
        description: 'Cargo profile to use for building (debug, release)'
        default: 'release'
        type: string
      enable-cache:
        description: 'Enable caching of dependencies'
        default: true
        type: boolean
      publish-crates-io:
        description: 'Publish package to crates.io'
        default: false
        type: boolean
      upload-artifact:
        description: 'Upload build artifact'
        default: false
        type: boolean
      artifact-name:
        description: 'Name of the artifact to upload'
        type: string
        required: false
      artifact-path:
        description: 'Path to the artifact to upload'
        type: string
        required: false
    secrets:
      CRATES_IO_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.set-output.outputs.build_success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust-version }}
          override: true

      - name: Cache dependencies
        if: ${{ inputs.enable-cache }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --profile ${{ inputs.build-target }}

      - name: Run tests
        run: cargo test --profile ${{ inputs.build-target }}

      - name: Set build success output
        id: set-output
        run: echo "build_success=true" >> $GITHUB_OUTPUT

      - name: Upload artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

  publish:
    needs: build
    if: ${{ inputs.publish-crates-io && needs.build.outputs.build_success == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust-version }}
          override: true

      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Package for crates.io
        run: cargo package

      - name: Publish to crates.io
        run: cargo publish