name: Build, Test and Publish Rust Package

on:
  workflow_call:
    inputs:
      rust-version:
        description: 'Rust version to use'
        default: 'stable'
        type: string
      working-directory:
        description: 'The directory to run jobs from'
        default: '.'
        type: string
      enable-cache:
        description: 'Enable caching of dependencies'
        default: true
        type: boolean
      publish-crates-io:
        description: 'Publish package to crates.io'
        default: false
        type: boolean
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: false

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # @master 2026-09-04 (action has no version tags)
        with:
          toolchain: ${{ inputs.rust-version }}
          components: clippy, rustfmt

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Cache dependencies
        if: ${{ inputs.enable-cache }}
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        working-directory: ${{ inputs.working-directory }}
        run: cargo fmt --all -- --check

      - name: Run linter (Clippy)
        working-directory: ${{ inputs.working-directory }}
        run: cargo clippy --locked --all-targets -- -D warnings

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: cargo build --locked --release

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: cargo test --locked --release

      - name: Check documentation
        working-directory: ${{ inputs.working-directory }}
        env:
          RUSTDOCFLAGS: '-D warnings'
        run: cargo doc --locked --no-deps --document-private-items

      - name: Validate package
        if: ${{ inputs.publish-crates-io }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo package --locked

      - name: Publish to crates.io
        if: ${{ inputs.publish-crates-io }}
        working-directory: ${{ inputs.working-directory }}
        run: cargo publish --locked
