name: Close stale issues and PRs

on:
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 30  # Marks issues as stale after 30 days of inactivity
          days-before-issue-close: 7   # Closes stale issues after an additional 7 days
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity."
          days-before-pr-stale: 60     # Marks PRs as stale after 60 days of inactivity
          days-before-pr-close: 14     # Closes stale PRs after an additional 14 days
          stale-pr-label: "stale"
          stale-pr-message: "This pull request has been automatically marked as stale due to inactivity."
